export  'package:widgets/presentation/screens/animated/animated_screen.dart';
export  'package:widgets/presentation/screens/app_tutorial/tutorial_screen.dart';
export  'package:widgets/presentation/screens/botones/buttons_screnn.dart';
export  'package:widgets/presentation/screens/card/cards_screen.dart';
export  'package:widgets/presentation/screens/home/home_screen.dart';
export  'package:widgets/presentation/screens/infinite_scroll/infinite_scroll_screen.dart';
export  'package:widgets/presentation/screens/progress/progress_screnn.dart';
export  'package:widgets/presentation/screens/snackbar/snackbar_screen.dart';
export  'package:widgets/presentation/screens/ui_controls/ui_controls_screnn.dart';
